sonar.projectKey=imageforge
sonar.projectName=ImageForge
sonar.projectVersion=1.0

sonar.sources=app
sonar.tests=app/tests

sonar.python.version=3.12

sonar.exclusions=**/__pycache__/**,**/*.pyc

sonar.test.inclusions=app/tests/**/*.py